### ISSUE TITLE
Issue nach lesen löschen

### ISSUE THREAD

**Issue by deulf** [HenningBeyer/IMoJIE_with_GRU_decoder#1]
Hey, ich bin die Person welche den zweiten Platz bei Jufo(Informatik) belegt hat. Du gehst auch zur ARS? 
PS Meine Email ist: lino.riepenhausen@gmail.com 

@HenningBeyer

**Comment by HenningBeyer** [comment]
Ja, genau. Momentan besuche ich dort die 12. Klasse.
Bei Interesse können wir uns gerne einmal austauschen.

Mit freundlichen Grüßen
Henning Beyer

Am Sa., 5. März 2022 um 17:11 Uhr schrieb deulf ***@***.***>:

**Comment by deulf** [comment]
Gerne, hast du eine Kontakmöglichkeit?

**Comment by HenningBeyer** [comment]
Ja, per Mail: ***@***.*** oder einfach per Konferenz (Zoom,BBB,
Discord, ...).

Mit freundlichen Grüßen
Henning Beyer

deulf ***@***.***> schrieb am Mo., 7. März 2022, 09:44:

**Comment by deulf** [comment]
Die Mail wird auf Github nicht angezeigt. Mein Discord Tag ist: deulf#8714 

LG Lino
